### ISSUE TITLE
click animation overflow 

### ISSUE THREAD

**Issue by AballahEhab** [codenameakshay/flutter-floating-bottom-bar#4]
**animation over flow the rounded bar  on click** 

![image](https://user-images.githubusercontent.com/52103437/195971441-eaf7ebe2-a3be-4da8-b15b-3aa0e172f3a2.png)

### suggestion
>  it would be more customizable if the box decoration became a property instead of only the color

**Comment by codenameakshay** [comment]
This is fixed and available in v1.2.0
