### ISSUE TITLE
How to place the bar in the top of the screen?

### ISSUE THREAD

**Issue by moshe5745** [codenameakshay/flutter-floating-bottom-bar#5]
Can the bar be placed on top of the screen instead of the bottom?
I try the alignment property without success.

**Comment by codenameakshay** [comment]
For any previous version (before v1.2.0) you can use the following code to make it at the top - 
<img width="800" alt="image" src="https://github.com/codenameakshay/flutter-floating-bottom-bar/assets/60510869/f18c915b-1dfb-490a-a654-6977962d56ae">

You can use the following properties on the latest version v1.2.0 to achieve the bar placement on top of screen -

<img width="638" alt="image" src="https://github.com/codenameakshay/flutter-floating-bottom-bar/assets/60510869/158ebc80-5a12-4db5-b2bf-a05847331e32">

https://github.com/codenameakshay/flutter-floating-bottom-bar/assets/60510869/b5c088f7-e6d0-4cbc-99e5-3121175b539e
